# Generated by Django 5.1.6 on 2025-03-02 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_delete_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2000)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('headers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='accounts.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_destinations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_destinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('received_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.account')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='destinations.destination')),
            ],
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['url'], name='destination_url_7f6d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['account', 'http_method'], name='destination_account_6a1849_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['event_id'], name='destination_event_i_4da77c_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['account', 'status'], name='destination_account_9d10f8_idx'),
        ),
    ]
