# Generated by Django 5.1.6 on 2025-03-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
