# Generated by Django 5.1.6 on 2025-03-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email_alter_role_role_name'),
    ]

    operations = [
    ]
