# Generated by Django 5.1.6 on 2025-03-02 (auto-generated, manually edited)
from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.bulk_create([
        Role(role_name='Admin'),
        Role(role_name='Normal user'),
    ])

def remove_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(role_name__in=['Admin', 'Normal user']).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20250302_0721'),  # Matches your 0006 timestamp
    ]
    operations = [
        migrations.RunPython(create_roles, remove_roles),
    ]