# Generated by Django 5.1.6 on 2025-03-02 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0005_alter_customuser_email_alter_role_role_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='url',
            field=models.URLField(db_index=True, max_length=2000),
        ),
        migrations.AddIndex(
            model_name='accountmember',
            index=models.Index(fields=['account', 'user'], name='accounts_ac_account_0965b2_idx'),
        ),
    ]
