# Generated by Django 5.1.6 on 2025-03-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_name_alter_destination_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
