# Generated by Django 5.1.6 on 2025-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='app_secret_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
